sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HI2fTppTHf31lUpFbtwP/XAv7u4eDSB+0jomYgsqYCg18TNPaprWQJoya81SXzcY5fRNLqFYXMeboWVuk/eT3hpjlMqFynZN0nS81PWXxGK9P5rsa5HMfr5f8mPzH9eoZ29xqzFIl35CNckl4bi7Vhh4deBut3M2OsGuFgHmpmtWVDH6mlukmXgk1BeBx8N8/ykxV16MvjYjzQ7MeheCro+eXbZ4XnX3PlamvZMZvzgPfii15ThOnP7UE4bUw9KJ4ctBgDRDowIihgrrYJXlwdocY/wI188rSnG0GcUrXHiZVauys0Xp9VMVP7nqN8sck7Re64onAB1sSJeTY6KBMigsjfzg4X/FPRBgmK8b9IaLmTrGIgW1Fyb89rh4L4bA8Bi9GGtARJFH5yx2dmubCyIhzZxp+0P9f8/k7eo6ZwL7MuMQ0WusDh8RKN/KAScodbBhoFFBuuY0xgU2DAYeIrIKA1HhkbBYNFqRWZ6ubN8zu6LWRQ/OMdW6dfZewftKyt8QqKDnWyoVC8p0DA7/CLne0jI4CAWW6Ykh61jvT6smJRE+Ja/fE0lMOGcugip0bEFHVdHPVEfr3oGP9nUI3NfNMvgu4+EWWacddiE6kMe8YT229POA+ByYSHzUZf0TYqnGR2ioNDStvhSznrpZmUPPBjqweX7t9glkcRfTUAg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Confessio-Amantis--Or-Tales-of-the-Seven-Deadly-Sins_266
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy